### ISSUE TITLE
I want to the monitor the screen  of the others.            

### ISSUE THREAD

**Issue by Boopalan-M** [indradhanush/WebRTC-Monitor#2]
In my application i want to add the screen minitoring when they click the login button how can i achieve that.

Thanks in advance!!!

**Comment by indradhanush** [comment]
@Boopalan-M This repository was created as a tool to test a webrtc service and report errors if any. Your question does not seem related to this repository and feels like a more generic question about WebRTC itself. Unfortunately I do know the answer to your question. Maybe you could ask on StackOverflow and hopefully you get a more informed answer there. Best of luck!
